type User @table {
  displayName: String!
  email: String
  photoUrl: String
  createdAt: Timestamp!
}

type JournalEntry @table {
  user: User!
  content: String!
  entryDate: Date!
  moodRating: Int
  isPrivate: Boolean
  createdAt: Timestamp!
  updatedAt: Timestamp!
}

type Tag @table {
  name: String!
  description: String
  createdAt: Timestamp!
}

type EntryTag @table(key: ["journalEntry", "tag"]) {
  journalEntry: JournalEntry!
  tag: Tag!
  createdAt: Timestamp!
}

type Intention @table {
  user: User!
  text: String!
  intentionDate: Date!
  isAchieved: Boolean
  createdAt: Timestamp!
  updatedAt: Timestamp!
}